# Generated by Django 4.2.7 on 2024-05-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('require', models.CharField(max_length=200, null=True)),
                ('description', models.TextField()),
                ('start_time', models.DateField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
